/**
 * Thèmes intégrés à Strok — disponibles d'emblée, sans rien importer.
 *
 * Un thème = un manifeste + une table de variables CSS (cf. THEME_TOKENS dans
 * themeHost.js). Appliquer un thème pose ces variables sur :root ; comme tout le
 * style de l'app en dépend (global.css), un thème repeint toute l'interface.
 *
 * Le thème « défaut » reproduit les valeurs de global.css : il sert d'aperçu et
 * de référence. L'appliquer revient simplement à retirer toute surcharge.
 */

export const DEFAULT_THEME_ID = '@builtin/default';

export const BUILTIN_THEMES = [
  {
    file: DEFAULT_THEME_ID,
    builtin: true,
    manifest: {
      id: DEFAULT_THEME_ID,
      name: 'Strok (défaut)',
      version: '1.0.0',
      author: 'Strok',
      description: 'Le thème sombre minimaliste d’origine.',
    },
    variables: {
      '--bg-app': '#0d0d0d',
      '--bg-canvas-area': '#0d0d0d',
      '--bg-panel': '#1a1a1a',
      '--bg-panel-2': '#151515',
      '--bg-titlebar': '#161616',
      '--bg-rail': '#141414',
      '--surface-hover': '#222222',
      '--surface-active': '#2a2a2a',
      '--surface-input': '#111111',
      '--border': '#2a2a2a',
      '--border-soft': '#232323',
      '--border-strong': '#333333',
      '--text': '#aaaaaa',
      '--text-dim': '#6b6b6b',
      '--text-bright': '#e8e8e8',
      '--icon': '#8a8a8a',
      '--icon-hover': '#d0d0d0',
      '--icon-active': '#f2f2f2',
      '--accent': '#e8e8e8',
      '--danger': '#e5484d',
    },
  },

  {
    file: '@builtin/light',
    builtin: true,
    manifest: {
      id: '@builtin/light',
      name: 'Clair',
      version: '1.0.0',
      author: 'Strok',
      description: 'Interface claire, encre bleue.',
    },
    variables: {
      '--bg-app': '#f4f4f5',
      '--bg-canvas-area': '#e9e9ec',
      '--bg-panel': '#ffffff',
      '--bg-panel-2': '#f6f6f7',
      '--bg-titlebar': '#ffffff',
      '--bg-rail': '#f0f0f2',
      '--surface-hover': '#ececef',
      '--surface-active': '#e0e0e4',
      '--surface-input': '#ffffff',
      '--border': '#e0e0e3',
      '--border-soft': '#ececec',
      '--border-strong': '#d2d2d6',
      '--text': '#44464b',
      '--text-dim': '#8a8d93',
      '--text-bright': '#18181b',
      '--icon': '#6b6e74',
      '--icon-hover': '#303135',
      '--icon-active': '#18181b',
      '--accent': '#2563eb',
      '--danger': '#e5484d',
    },
  },

  {
    file: '@builtin/midnight',
    builtin: true,
    manifest: {
      id: '@builtin/midnight',
      name: 'Nuit',
      version: '1.0.0',
      author: 'Strok',
      description: 'Bleu nuit profond, accent indigo.',
    },
    variables: {
      '--bg-app': '#0b0f1a',
      '--bg-canvas-area': '#0b0f1a',
      '--bg-panel': '#151b2e',
      '--bg-panel-2': '#111626',
      '--bg-titlebar': '#121829',
      '--bg-rail': '#0f1422',
      '--surface-hover': '#1d2540',
      '--surface-active': '#26304f',
      '--surface-input': '#0d121f',
      '--border': '#232c45',
      '--border-soft': '#1c2438',
      '--border-strong': '#2e3a5c',
      '--text': '#9aa7c7',
      '--text-dim': '#5d6788',
      '--text-bright': '#e6ebf7',
      '--icon': '#7e8aad',
      '--icon-hover': '#c2cce6',
      '--icon-active': '#eef2fb',
      '--accent': '#6d8bff',
      '--danger': '#ff5a6a',
    },
  },

  {
    file: '@builtin/nord',
    builtin: true,
    manifest: {
      id: '@builtin/nord',
      name: 'Nord',
      version: '1.0.0',
      author: 'Strok',
      description: 'Palette arctique froide et douce.',
    },
    variables: {
      '--bg-app': '#2e3440',
      '--bg-canvas-area': '#2b303b',
      '--bg-panel': '#3b4252',
      '--bg-panel-2': '#343b4a',
      '--bg-titlebar': '#353c4a',
      '--bg-rail': '#323846',
      '--surface-hover': '#434c5e',
      '--surface-active': '#4c566a',
      '--surface-input': '#2e3440',
      '--border': '#434c5e',
      '--border-soft': '#3b4252',
      '--border-strong': '#4c566a',
      '--text': '#d8dee9',
      '--text-dim': '#7b8494',
      '--text-bright': '#eceff4',
      '--icon': '#aebacf',
      '--icon-hover': '#e5e9f0',
      '--icon-active': '#eceff4',
      '--accent': '#88c0d0',
      '--danger': '#bf616a',
    },
  },

  {
    file: '@builtin/sepia',
    builtin: true,
    manifest: {
      id: '@builtin/sepia',
      name: 'Sépia',
      version: '1.0.0',
      author: 'Strok',
      description: 'Tons chauds papier, accent ambre.',
    },
    variables: {
      '--bg-app': '#2a2422',
      '--bg-canvas-area': '#2a2422',
      '--bg-panel': '#36302c',
      '--bg-panel-2': '#2f2a26',
      '--bg-titlebar': '#332d29',
      '--bg-rail': '#302a26',
      '--surface-hover': '#443c36',
      '--surface-active': '#52473f',
      '--surface-input': '#261f1c',
      '--border': '#463e37',
      '--border-soft': '#3a332e',
      '--border-strong': '#574c43',
      '--text': '#c9bba9',
      '--text-dim': '#8a7c6b',
      '--text-bright': '#f3e9d8',
      '--icon': '#b3a48f',
      '--icon-hover': '#e2d4bf',
      '--icon-active': '#f3e9d8',
      '--accent': '#d8a657',
      '--danger': '#e5484d',
    },
  },
];
